---
extends: default

# Ignore Justfiles - they use Just syntax, not YAML
ignore: |
  Justfile
  justfile

rules:
  line-length:
    max: 100
    level: warning
  trailing-spaces:
    level: error
  indentation:
    spaces: consistent
    indent-sequences: consistent
