---
services:
  gluetun:
    image: 'qmcgaw/gluetun:latest'
    container_name: gluetun
    networks:
      dvr:
        ipv4_address: 192.168.5.110
    cap_add:
      - NET_ADMIN
    ports:
      - 7878:7878/tcp
      - 8080:8080/tcp
      - 8686:8686/tcp
      - 8787:8787/tcp
      - 9117:9117/tcp
      - 8090:8090/tcp
      - 5076:5076/tcp
      - 444:444/tcp
      - 8989:8989/tcp
      - 9091:9091/tcp
    environment:
      - PUID=1027
      - PGID=100
      - TZ=Australia/Sydney
      - VPN_SERVICE_PROVIDER=private internet access
      - OPENVPN_USER=REDACTED
      - OPENVPN_PASSWORD=REDACTED
      - SERVER_REGIONS=Netherlands
      - VPN_PORT_FORWARDING=on
      - VPN_PORT_FORWARDING_STATUS_FILE=/gluetun/portfwd
      - UPDATER_VPN_SERVICE_PROVIDER=private internet access
      - UPDATE_PERIOD=24h
      - BLOCK_MALICIOUS=on
      - BLOCK_SURVEILLANCE=on
      - BLOCK_ADS=on
    volumes:
      - '/volume1/dkrcfg/gluetun:/gluetun'
    restart: always
    security_opt:
      - no-new-privileges:true
  nzbhydra:
    image: 'lscr.io/linuxserver/nzbhydra2:latest'
    container_name: nzbhydra
    depends_on:
      - gluetun
    network_mode: "service:gluetun"
    environment:
      - PUID=1027
      - PGID=100
      - TZ=Australia/Sydney
    volumes:
      - '/volume1/dkrcfg/nzbhydra:/config'
    restart: always
  jackett:
    image: 'lscr.io/linuxserver/jackett:latest'
    container_name: jackett
    depends_on:
      - gluetun
    network_mode: "service:gluetun"
    environment:
      - PUID=1027
      - PGID=100
      - TZ=Australia/Sydney
    volumes:
      - '/volume1/dkrcfg/jackett:/config'
    restart: always
  sabnzbd:
    image: 'lscr.io/linuxserver/sabnzbd:latest'
    container_name: sabnzbd
    depends_on:
      - gluetun
    network_mode: "service:gluetun"
    environment:
      - PUID=1027
      - PGID=100
      - TZ=Australia/Sydney
    volumes:
      - '/volume1/dkrcfg/sabnzbd:/config'
      - '/volume1/downloads:/downloads'
    restart: always
  transmission:
    image: 'lscr.io/linuxserver/transmission:latest'
    container_name: transmission 
    depends_on:
      - gluetun
    network_mode: "service:gluetun"
    environment:
      - PUID=1027
      - PGID=100
      - TZ=Australia/Sydney
      - PASS=REDACTED
      - FILE__PEERPORT=/volume1/dkrcfg/gluetun/portfwd
    volumes:
      - '/volume1/dkrcfg/transmission:/config'
      - '/volume1/downloads:/downloads'
    restart: always
  sonarr:
    image: 'lscr.io/linuxserver/sonarr:latest'
    container_name: sonarr
    depends_on:
      - gluetun
    network_mode: "service:gluetun"
    environment:
      - PUID=1027
      - PGID=100
      - TZ=Australia/Sydney
    volumes:
      - '/volume1/TV:/tv'
      - '/volume1/dkrcfg/sonarr:/config'
      - '/volume1/downloads:/downloads'
    restart: always
  radarr:
    image: 'lscr.io/linuxserver/radarr:latest'
    container_name: radarr
    depends_on:
      - gluetun
    network_mode: "service:gluetun"
    environment:
      - PUID=1027
      - PGID=100
      - TZ=Australia/Sydney
    volumes:
      - '/volume1/Movies:/movies'
      - '/volume1/dkrcfg/radarr:/config'
      - '/volume1/downloads:/downloads'
    restart: always
  lidarr:
    image: 'lscr.io/linuxserver/lidarr:latest'
    container_name: lidarr
    depends_on:
      - gluetun
    network_mode: "service:gluetun"
    environment:
      - PUID=1027
      - PGID=100
      - TZ=Australia/Sydney
    volumes:
      - '/volume1/Music:/music'
      - '/volume1/dkrcfg/lidarr:/config'
      - '/volume1/downloads:/downloads'
  mylar:
    image: 'lscr.io/linuxserver/mylar3:latest'
    container_name: mylar
    depends_on:
      - gluetun
    network_mode: "service:gluetun"
    environment:
      - PUID=1027
      - PGID=100
      - TZ=Australia/Sydney
    volumes:
      - '/volume1/Comics:/comics'
      - '/volume1/dkrcfg/mylar:/config'
      - '/volume1/downloads:/downloads'
    restart: always
  readarr:
    image: 'lscr.io/linuxserver/readarr:nightly-0.4.19.2811-ls400'
    container_name: readarr
    depends_on:
      - gluetun
    network_mode: "service:gluetun"
    environment:
      - PUID=1027
      - PGID=100
      - TZ=Australia/Sydney
    volumes:
      - '/volume1/Books:/books'
      - '/volume1/dkrcfg/readarr:/config'
      - '/volume1/downloads:/downloads'
    restart: always
  heimdall:
    image: 'lscr.io/linuxserver/heimdall:latest'
    container_name: heimdall
    network_mode: "host"
    environment:
      - PUID=1027
      - PGID=100
      - TZ=Australia/Sydney
    volumes:
      - '/volume1/dkrcfg/heimdall:/config'
    restart: always
networks:
  dvr:
    driver: macvlan
    driver_opts:
      parent: eth0
    ipam:
      config:
        - subnet: 192.168.5.0/24
          gateway: 192.168.5.1