---
services:
  gluetun:
    image: 'qmcgaw/gluetun:latest'
    container_name: gluetun
    networks:
      - gluetun
    cap_add:
      - NET_ADMIN
    ports:
      - 7878:7878/tcp
      - 8080:8080/tcp
      - 8686:8686/tcp
      - 8787:8787/tcp
      - 9117:9117/tcp
      - 8090:8090/tcp
      - 5076:5076/tcp
      - 444:444/tcp
      - 8989:8989/tcp
      - 9091:9091/tcp
    environment:
      - PUID=1027
      - PGID=100
      - TZ=Australia/Sydney
      - VPN_SERVICE_PROVIDER=private internet access
      - OPENVPN_USER=REDACTED
      - OPENVPN_PASSWORD=REDACTED
      - SERVER_REGIONS=Switzerland
      - VPN_PORT_FORWARDING=on
      - VPN_PORT_FORWARDING_STATUS_FILE=/gluetun/portfwd
      - UPDATER_VPN_SERVICE_PROVIDER=private internet access
      - UPDATE_PERIOD=24h
      - BLOCK_MALICIOUS=on
      - BLOCK_SURVEILLANCE=on
      - BLOCK_ADS=on
    volumes:
      - '/volume1/dkrcfg/gluetun:/gluetun'
    restart: always
    security_opt:
      - no-new-privileges:true
  nzbhydra:
    image: 'lscr.io/linuxserver/nzbhydra2:latest'
    container_name: nzbhydra
    depends_on:
      - gluetun
    network_mode: "service:gluetun"
    environment:
      - PUID=1027
      - PGID=100
      - TZ=Australia/Sydney
    volumes:
      - '/volume1/dkrcfg/nzbhydra:/config'
    restart: always
networks:
   gluetun: null